### ISSUE TITLE
request: remove my repo

### ISSUE THREAD

**Issue by krvstek** [Jman-Github/Awesome-ReVanced#1]
Hello,

Thank you for your interest in my project and for including my repository on your list. I would like to inform you that for personal reasons I have decided to stop maintaining this repository. As a result, it has been deleted and is no longer available.

It is important to me that your list is up to date and contains only active and supported projects, so I kindly ask you to remove my repository from your list.

Thank you for your understanding and support! If you have any questions or need help, please let me know.

Best regards,
krvstek.

**Comment by Jman-Github** [comment]
Thanks for letting me know! The list has been updated accordingly.
